language: java
before_deploy:
  - ant dist
deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: "release/pl.sternik.pb.robocode.ProBot_*.jar"
  skip_cleanup: true
  on:
    tags: true